package com.bit.coin.p2p.production;

public enum P2PErrorCode {
    INVALID_ADDRESS,
    BLACKLISTED,
    CONNECT_FAILED,
    DISCONNECT_FAILED,
    PEER_NOT_CONNECTED,
    SEND_FRAME_FAILED,
    SEND_MESSAGE_FAILED,
    RECEIVE_DECRYPT_FAILED,
    FLOW_CONTROL_REJECTED,
    CONGESTION_TIMEOUT,
    REMOTE_CLOSED,
    INTERNAL_ERROR
}
